Abc/Abc.Northwind.MvcWebUI/Controllers/ProductController.cs
using Abc.Northwind.Business.Abstract;
using Abc.Northwind.MvcWebUI.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Abc.Northwind.MvcWebUI.Controllers
{
	public class ProductController : Controller
	{
		private IProductService _productService;

		public ProductController(IProductService productService)
		{
			_productService = productService;
		}

		public ActionResult Index(int page = 1, int category = 0)
		{

			int pageSize = 10;

			var products = _productService.GetByCategory(category);

			ProductListViewModel model = new ProductListViewModel
			{
				Products = products.Skip((page - 1) * pageSize).Take(pageSize).ToList(),
				PageCount = (int)Math.Ceiling(products.Count / (double)pageSize),
				PageSize = pageSize,
				CurrentCategory = category,
				CurrentPage = page
			};

			return View(model);
		}

		//public string Session()
		//{
		//	HttpContext.Session.SetString("city", "Ankara");
		//	HttpContext.Session.SetInt32("age", 26);

		//	HttpContext.Session.GetString("city");
		//	HttpContext.Session.GetInt32("age");

		//	return "";
		//}

		
	}
}

Abc/Abc.Northwind.MvcWebUI/ViewComponents/CartSummaryViewComponent.cs
using Abc.Northwind.MvcWebUI.Models;
using Abc.Northwind.MvcWebUI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Abc.Northwind.MvcWebUI.ViewComponents
{
	public class CartSummaryViewComponent : ViewComponent
	{
		ICartSessionService _cartSessionService;

		public CartSummaryViewComponent(ICartSessionService cartSessionService)
		{
			_cartSessionService = cartSessionService;
		}

		public ViewViewComponentResult Invoke()
		{
			var model = new CartSummaryViewModel
			{
				Cart = _cartSessionService.GetCart()
			};

			return View(model);
		}
	}
}

Abc/Abc.Northwind.MvcWebUI/ViewComponents/CategoryListViewComponent.cs
using Abc.Northwind.Business.Abstract;
using Abc.Northwind.MvcWebUI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Abc.Northwind.MvcWebUI.ViewComponents
{
	public class CategoryListViewComponent : ViewComponent
	{
		private ICategoryService _categoryService;
		public CategoryListViewComponent(ICategoryService categoryService)
		{
			_categoryService = categoryService;
		}

		public ViewViewComponentResult Invoke()
		{
			var model = new CategoryListViewModel
			{
				Categories = _categoryService.GetAll(),
				CurrentCategory = Convert.ToInt32(HttpContext.Request.Query["category"])
			};

			return View(model);
		}
	}
}

Abc/Abc.Northwind.MvcWebUI/ViewComponents/UserSummaryViewComponent.cs
using Abc.Northwind.MvcWebUI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Abc.Northwind.MvcWebUI.ViewComponents
{
	public class UserSummaryViewComponent : ViewComponent
	{
		public ViewViewComponentResult Invoke()
		{

			UserDetailsViewModel model = new UserDetailsViewModel
			{
				UserName = HttpContext.User.Identity.Name
			};

			return View(model);
		}
	}
}

Abc/Abc.Northwind.MvcWebUI/Views/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.Title</title>
	<link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
	<script src="~/node_modules/jquery/dist/jquery.min.js"></script>
	<script src="~/node_modules/bootstrap/dist/js/bootstrap.js"></script>
	<script src="~/node_modules/jquery-validation/dist/jquery.validate.js"></script>
	<script src="~/node_modules/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
	<script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>
</head>
<body>
	<div class="col-md-12">
		<nav class="navbar navbar-default">
			<div class="container-fluid">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="#">Northwind Admin Panel</a>
				</div>

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li class="active"><a asp-controller="Product" asp-action="Index">Products Store<span class="sr-only">(current)</span></a></li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User <span class="caret"></span></a>
							@await Component.InvokeAsync("UserSummary")
							
						</li>
					</ul>
				</div><!-- /.navbar-collapse -->
			</div><!-- /.container-fluid -->
		</nav>
	</div>
	<div  class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
		@if (TempData["message"] != null)
		{
			<div class="alert alert-info" role="alert">@TempData["message"]</div>
		}
		@RenderBody()
	</div>
	<div class="col-md-3">
		<div class="LI-profile-badge" data-version="v1" data-size="small" data-locale="tr_TR" data-type="vertical" data-theme="dark" data-vanity="sevgi-akten-5221b9a8"><a class="LI-simple-link" href='https://tr.linkedin.com/in/sevgi-akten-5221b9a8?trk=profile-badge'>Sevgi AKTEN</a></div>
	</div>
	<div class="col-md-12">@DateTime.Now.Year - All Copy Right - Sevgi AKTEN </div>
</body>
</html>

Abc/Abc.Northwind.MvcWebUI/Views/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.Title</title>
	<link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
	<script src="~/node_modules/jquery/dist/jquery.min.js"></script>
	<script src="~/node_modules/bootstrap/dist/js/bootstrap.js"></script>
	<script src="~/node_modules/jquery-validation/dist/jquery.validate.js"></script>
	<script src="~/node_modules/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
	<script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>
</head>
<body>
	<div class="col-md-12">
		<nav class="navbar navbar-default">
			<div class="container-fluid">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="#">Northwind</a>
				</div>

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li class="active"><a asp-controller="Account" asp-action="Login">Admin<span class="sr-only">(current)</span></a></li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Cart <span class="caret"></span></a>
							@await Component.InvokeAsync("CartSummary")
						</li>
					</ul>
				</div><!-- /.navbar-collapse -->
			</div><!-- /.container-fluid -->
		</nav>
	</div>
	<div class="col-md-2">
		@await Component.InvokeAsync("CategoryList")
	</div>
	<div class="col-md-7">
		@if (TempData["message"] != null)
		{
			<div class="alert alert-info" role="alert">@TempData["message"]</div>
		}
		@RenderBody()
	</div>
	<div class="col-md-3">
		<div class="LI-profile-badge" data-version="v1" data-size="small" data-locale="tr_TR" data-type="vertical" data-theme="dark" data-vanity="sevgi-akten-5221b9a8"><a class="LI-simple-link" href='https://tr.linkedin.com/in/sevgi-akten-5221b9a8?trk=profile-badge'>Sevgi AKTEN</a></div>
	</div>
	<div class="col-md-12">Foooter</div>
</body>
</html>